import { createClientFromRequest } from 'npm:@base44/sdk@0.8.4';
import { jsPDF } from 'npm:jspdf@2.5.1';

Deno.serve(async (req) => {
    try {
        const base44 = createClientFromRequest(req);
        const user = await base44.auth.me();

        if (!user) {
            return Response.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const { strategy_id, format = 'pdf' } = await req.json();

        if (!strategy_id) {
            return Response.json({ error: 'strategy_id is required' }, { status: 400 });
        }

        const strategies = await base44.entities.Strategy.filter({ id: strategy_id });
        
        if (strategies.length === 0) {
            return Response.json({ error: 'Strategy not found' }, { status: 404 });
        }

        const strategy = strategies[0];

        if (format === 'pdf') {
            const doc = new jsPDF();

            // Header
            doc.setFontSize(24);
            doc.setTextColor(59, 130, 246);
            doc.text('CAIO Strategic Intelligence', 20, 20);

            doc.setFontSize(20);
            doc.setTextColor(0, 0, 0);
            doc.text(strategy.title, 20, 40);

            // Category badge
            doc.setFontSize(10);
            doc.setTextColor(139, 92, 246);
            doc.text(`Framework: ${strategy.category}`, 20, 50);

            // Description
            doc.setFontSize(12);
            doc.setTextColor(100, 100, 100);
            const description = doc.splitTextToSize(strategy.description || 'No description provided', 170);
            doc.text(description, 20, 65);

            let yPos = 85;

            // Key Insights
            if (strategy.key_insights && strategy.key_insights.length > 0) {
                doc.setFontSize(14);
                doc.setTextColor(0, 0, 0);
                doc.text('Key Insights', 20, yPos);
                yPos += 10;

                doc.setFontSize(10);
                doc.setTextColor(60, 60, 60);
                strategy.key_insights.forEach((insight, idx) => {
                    const lines = doc.splitTextToSize(`${idx + 1}. ${insight}`, 170);
                    doc.text(lines, 25, yPos);
                    yPos += lines.length * 5 + 3;

                    if (yPos > 270) {
                        doc.addPage();
                        yPos = 20;
                    }
                });
                yPos += 10;
            }

            // ROI Estimate
            if (strategy.roi_estimate) {
                doc.setFontSize(12);
                doc.setTextColor(16, 185, 129);
                doc.text(`Estimated ROI: ${strategy.roi_estimate}%`, 20, yPos);
                yPos += 10;
            }

            // Priority
            if (strategy.priority) {
                doc.setFontSize(12);
                doc.setTextColor(234, 88, 12);
                doc.text(`Priority: ${strategy.priority.toUpperCase()}`, 20, yPos);
                yPos += 10;
            }

            // Action Items
            if (strategy.action_items && strategy.action_items.length > 0) {
                if (yPos > 250) {
                    doc.addPage();
                    yPos = 20;
                }

                doc.setFontSize(14);
                doc.setTextColor(0, 0, 0);
                doc.text('Action Items', 20, yPos);
                yPos += 10;

                doc.setFontSize(10);
                strategy.action_items.forEach((item, idx) => {
                    if (yPos > 270) {
                        doc.addPage();
                        yPos = 20;
                    }

                    doc.setTextColor(0, 0, 0);
                    doc.text(`${idx + 1}. ${item.task}`, 25, yPos);
                    yPos += 5;

                    doc.setTextColor(100, 100, 100);
                    if (item.deadline) {
                        doc.text(`   Deadline: ${item.deadline}`, 25, yPos);
                        yPos += 5;
                    }
                    if (item.responsible) {
                        doc.text(`   Responsible: ${item.responsible}`, 25, yPos);
                        yPos += 5;
                    }
                    yPos += 3;
                });
            }

            // Footer
            const pageCount = doc.internal.getNumberOfPages();
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i);
                doc.setFontSize(8);
                doc.setTextColor(150, 150, 150);
                doc.text(
                    `Generated by CAIO • ${new Date().toLocaleDateString()} • Page ${i} of ${pageCount}`,
                    doc.internal.pageSize.getWidth() / 2,
                    doc.internal.pageSize.getHeight() - 10,
                    { align: 'center' }
                );
            }

            const pdfBytes = doc.output('arraybuffer');

            return new Response(pdfBytes, {
                status: 200,
                headers: {
                    'Content-Type': 'application/pdf',
                    'Content-Disposition': `attachment; filename="${strategy.title.replace(/[^a-z0-9]/gi, '_')}.pdf"`
                }
            });
        }

        // JSON export
        return Response.json({
            success: true,
            data: strategy
        });

    } catch (error) {
        console.error('Export error:', error);
        return Response.json({ 
            error: error.message,
            stack: error.stack 
        }, { status: 500 });
    }
});