import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';
import { jsPDF } from 'npm:jspdf@2.5.1';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { format = 'pdf', graph_data, anomalies, predictions, influencers } = await req.json();

    const { nodes, relationships } = graph_data;

    // Compile report data
    const reportData = {
      generated_at: new Date().toISOString(),
      generated_by: user.email,
      network_summary: {
        total_nodes: nodes?.length || 0,
        total_relationships: relationships?.length || 0,
        node_types: [...new Set(nodes?.map(n => n.node_type))],
        avg_connections: relationships?.length > 0 ? (relationships.length * 2 / nodes.length).toFixed(2) : 0
      },
      anomalies_summary: {
        total: anomalies?.length || 0,
        critical: anomalies?.filter(a => a.severity === 'critical').length || 0,
        high: anomalies?.filter(a => a.severity === 'high').length || 0,
        by_type: anomalies?.reduce((acc, a) => {
          acc[a.type] = (acc[a.type] || 0) + 1;
          return acc;
        }, {}) || {}
      },
      influencers_summary: {
        total: influencers?.length || 0,
        avg_influence_score: influencers?.length > 0 
          ? (influencers.reduce((sum, i) => sum + i.influence_score, 0) / influencers.length).toFixed(2)
          : 0,
        top_influencers: influencers?.slice(0, 10) || []
      },
      predictions_summary: predictions ? {
        predicted_relationships: predictions.predictions?.predicted_relationships?.length || 0,
        confidence_score: predictions.metadata?.confidence_score || 0,
        timeframe_days: predictions.metadata?.timeframe_days || 0,
        emerging_patterns: predictions.predictions?.emerging_patterns || []
      } : null
    };

    if (format === 'csv') {
      // Generate CSV
      let csv = 'Network Analysis Report\n\n';
      csv += `Generated at,${reportData.generated_at}\n`;
      csv += `Generated by,${reportData.generated_by}\n\n`;
      
      csv += 'Network Summary\n';
      csv += `Total Nodes,${reportData.network_summary.total_nodes}\n`;
      csv += `Total Relationships,${reportData.network_summary.total_relationships}\n`;
      csv += `Average Connections,${reportData.network_summary.avg_connections}\n\n`;
      
      csv += 'Top Anomalies\n';
      csv += 'Node Label,Type,Severity,Details\n';
      anomalies?.slice(0, 20).forEach(a => {
        csv += `"${a.node_label || 'N/A'}","${a.type}","${a.severity}","${(a.details || '').replace(/"/g, '""')}"\n`;
      });
      
      csv += '\nTop Influencers\n';
      csv += 'Label,Type,Influence Score,Degree,Betweenness,Closeness\n';
      influencers?.slice(0, 20).forEach(i => {
        csv += `"${i.label}","${i.node_type}",${i.influence_score.toFixed(2)},${i.degree},${i.betweenness.toFixed(2)},${i.closeness.toFixed(4)}\n`;
      });

      return new Response(csv, {
        headers: {
          'Content-Type': 'text/csv',
          'Content-Disposition': `attachment; filename=network-analysis-${Date.now()}.csv`
        }
      });
    } else {
      // Generate PDF
      const doc = new jsPDF();
      let y = 20;

      // Title
      doc.setFontSize(20);
      doc.setTextColor(10, 37, 64);
      doc.text('Network Intelligence Analysis Report', 20, y);
      y += 10;

      // Metadata
      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated: ${new Date(reportData.generated_at).toLocaleString()}`, 20, y);
      y += 5;
      doc.text(`By: ${reportData.generated_by}`, 20, y);
      y += 15;

      // Network Summary
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text('Network Summary', 20, y);
      y += 8;

      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      doc.text(`Total Nodes: ${reportData.network_summary.total_nodes}`, 30, y);
      y += 6;
      doc.text(`Total Relationships: ${reportData.network_summary.total_relationships}`, 30, y);
      y += 6;
      doc.text(`Average Connections: ${reportData.network_summary.avg_connections}`, 30, y);
      y += 6;
      doc.text(`Node Types: ${reportData.network_summary.node_types.join(', ')}`, 30, y);
      y += 12;

      // Anomalies Summary
      if (reportData.anomalies_summary.total > 0) {
        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text('Anomalies Detected', 20, y);
        y += 8;

        doc.setFontSize(10);
        doc.setTextColor(239, 68, 68);
        doc.text(`Critical: ${reportData.anomalies_summary.critical}`, 30, y);
        y += 6;
        doc.setTextColor(251, 146, 60);
        doc.text(`High: ${reportData.anomalies_summary.high}`, 30, y);
        y += 6;
        doc.setTextColor(60, 60, 60);
        doc.text(`Total: ${reportData.anomalies_summary.total}`, 30, y);
        y += 10;

        // Top anomalies
        doc.setFontSize(12);
        doc.setTextColor(0, 0, 0);
        doc.text('Top Anomalies:', 30, y);
        y += 6;

        anomalies?.slice(0, 5).forEach((anomaly, idx) => {
          if (y > 270) {
            doc.addPage();
            y = 20;
          }
          doc.setFontSize(9);
          doc.setTextColor(60, 60, 60);
          doc.text(`${idx + 1}. ${anomaly.node_label || 'Unknown'} (${anomaly.severity})`, 35, y);
          y += 5;
          doc.setFontSize(8);
          doc.setTextColor(100, 100, 100);
          const detailLines = doc.splitTextToSize(anomaly.details || '', 160);
          doc.text(detailLines, 40, y);
          y += detailLines.length * 4 + 4;
        });
        y += 8;
      }

      // Influencers Summary
      if (reportData.influencers_summary.total > 0) {
        if (y > 250) {
          doc.addPage();
          y = 20;
        }

        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text('Key Influencers', 20, y);
        y += 8;

        doc.setFontSize(10);
        doc.setTextColor(60, 60, 60);
        doc.text(`Average Influence Score: ${reportData.influencers_summary.avg_influence_score}`, 30, y);
        y += 10;

        doc.setFontSize(12);
        doc.text('Top 10 Influencers:', 30, y);
        y += 6;

        reportData.influencers_summary.top_influencers.forEach((influencer, idx) => {
          if (y > 270) {
            doc.addPage();
            y = 20;
          }
          doc.setFontSize(9);
          doc.setTextColor(60, 60, 60);
          doc.text(`${idx + 1}. ${influencer.label} - Score: ${influencer.influence_score.toFixed(1)}`, 35, y);
          y += 5;
          doc.setFontSize(8);
          doc.setTextColor(100, 100, 100);
          doc.text(`Type: ${influencer.node_type} | Connections: ${influencer.degree}`, 40, y);
          y += 6;
        });
        y += 8;
      }

      // Predictions Summary
      if (reportData.predictions_summary) {
        if (y > 250) {
          doc.addPage();
          y = 20;
        }

        doc.setFontSize(14);
        doc.setTextColor(0, 0, 0);
        doc.text('Network Predictions', 20, y);
        y += 8;

        doc.setFontSize(10);
        doc.setTextColor(60, 60, 60);
        doc.text(`Timeframe: ${reportData.predictions_summary.timeframe_days} days`, 30, y);
        y += 6;
        doc.text(`Confidence: ${reportData.predictions_summary.confidence_score.toFixed(1)}%`, 30, y);
        y += 6;
        doc.text(`Predicted Relationships: ${reportData.predictions_summary.predicted_relationships}`, 30, y);
        y += 10;

        if (reportData.predictions_summary.emerging_patterns.length > 0) {
          doc.setFontSize(12);
          doc.text('Emerging Patterns:', 30, y);
          y += 6;

          reportData.predictions_summary.emerging_patterns.slice(0, 5).forEach((pattern, idx) => {
            if (y > 270) {
              doc.addPage();
              y = 20;
            }
            doc.setFontSize(9);
            doc.setTextColor(100, 100, 100);
            const patternLines = doc.splitTextToSize(`• ${pattern}`, 160);
            doc.text(patternLines, 35, y);
            y += patternLines.length * 4 + 2;
          });
        }
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text('ESIOS CAIO - Strategic Intelligence Platform', 20, 285);

      const pdfBytes = doc.output('arraybuffer');

      return new Response(pdfBytes, {
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename=network-analysis-${Date.now()}.pdf`
        }
      });
    }

  } catch (error) {
    console.error("Error generating report:", error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});