import { createClientFromRequest } from 'npm:@base44/sdk@0.8.4';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { format, timeRange, metrics } = await req.json();

    // Fetch all analytics data
    const [strategies, conversations, analyses, nodes, relationships] = await Promise.all([
      base44.entities.Strategy.list(),
      base44.agents.listConversations({ agent_name: 'caio_agent' }),
      base44.entities.Analysis.list(),
      base44.entities.KnowledgeGraphNode.list(),
      base44.entities.KnowledgeGraphRelationship.list()
    ]);

    // Generate comprehensive report content
    const reportContent = `
# Analytics Report
Generated: ${new Date().toLocaleString()}
Period: ${timeRange}

## Executive Summary
- Total Strategies: ${strategies.length}
- Validated Strategies: ${strategies.filter(s => s.status === 'validated').length}
- Active Conversations: ${conversations.length}
- Knowledge Graph Nodes: ${nodes.length}
- Total Analyses: ${analyses.length}

## Strategic Performance
- Execution Rate: ${((strategies.filter(s => s.status === 'validated').length / strategies.length) * 100).toFixed(1)}%
- Average Confidence: ${(analyses.reduce((sum, a) => sum + (a.confidence_score || 0), 0) / analyses.length).toFixed(1)}%

## Knowledge Graph Metrics
- Total Nodes: ${nodes.length}
- Total Relationships: ${relationships.length}
- Network Density: ${(relationships.length / (nodes.length * (nodes.length - 1))).toFixed(4)}

## Framework Distribution
${strategies.reduce((acc, s) => {
  const fw = s.category || 'Unknown';
  acc[fw] = (acc[fw] || 0) + 1;
  return acc;
}, {})}

---
Report generated by CAIO·AI Analytics Engine
`;

    // For PDF format, you would integrate with a PDF generation library
    // For now, return markdown with download instructions
    if (format === 'pdf') {
      return Response.json({
        success: true,
        format: 'markdown',
        content: reportContent,
        message: 'PDF generation coming soon - markdown report provided',
        download_url: null
      });
    }

    return Response.json({
      success: true,
      format,
      content: reportContent
    });

  } catch (error) {
    console.error('Error generating report:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});