export const comparisonFeatures = [
  {
    feature: "Strategic Analysis Framework (TSI v9.3)",
    caio: true,
    llms: "Generic",
    reasoning: "Advanced",
    individual: true,
    boutique: true,
  },
  {
    feature: "Financial Modeling (DCF, Monte Carlo)",
    caio: true,
    llms: "Basic",
    reasoning: "Intermediate",
    individual: true,
    boutique: true,
  },
  {
    feature: "Competitive Intelligence Automation",
    caio: true,
    llms: false,
    reasoning: "Manual",
    individual: false,
    boutique: "Manual",
  },
  {
    feature: "Multi-Agent Orchestration (Hierarchical)",
    caio: true,
    llms: false,
    reasoning: false,
    individual: false,
    boutique: false,
  },
  {
    feature: "Knowledge Graph (strategic connections)",
    caio: true,
    llms: false,
    reasoning: false,
    individual: false,
    boutique: "Manual",
  },
  {
    feature: "Behavioral Intelligence (Client Archetypes)",
    caio: true,
    llms: false,
    reasoning: false,
    individual: "Limited",
    boutique: "Custom",
  },
  {
    feature: "Cognitive Governance (Hermes Trust-Broker)",
    caio: true,
    llms: false,
    reasoning: false,
    individual: false,
    boutique: false,
  },
  {
    feature: "Modular Expert Mode (M1–M11)",
    caio: true,
    llms: false,
    reasoning: false,
    individual: "Partial",
    boutique: true,
  },
  {
    feature: "Real-time Data Integration",
    caio: true,
    llms: "Via Plugins",
    reasoning: "Via Plugins",
    individual: "Manual",
    boutique: "Manual",
  },
  {
    feature: "Continuous Learning & Memory",
    caio: true,
    llms: false,
    reasoning: "Session",
    individual: true,
    boutique: true,
  },
  {
    feature: "Cost (annual)",
    caio: "$1,188–$47,880",
    llms: "$240–$2,400",
    reasoning: "$3,600–$12,000",
    individual: "$100K–$300K",
    boutique: "$250K–$1M+",
  },
  {
    feature: "Delivery Time",
    caio: "Minutes–Hours",
    llms: "Seconds",
    reasoning: "Minutes",
    individual: "Weeks–Months",
    boutique: "Months",
  },
];