export const comparisonFeatures = [
  {
    feature: "Strategic Analysis Framework (TSI v9.3 · 11 módulos)",
    caio: true,
    chatgpt: false,
    claude: false,
    consultants: true,
  },
  {
    feature: "Financial Modeling (DCF, Monte Carlo)",
    caio: true,
    chatgpt: false,
    claude: false,
    consultants: true,
  },
  {
    feature: "Competitive Intelligence Automation",
    caio: true,
    chatgpt: false,
    claude: false,
    consultants: false,
  },
  {
    feature: "Multi-Agent Orchestration (Hierarchical)",
    caio: true,
    chatgpt: false,
    claude: false,
    consultants: false,
  },
  {
    feature: "Knowledge Graph (strategic connections)",
    caio: true,
    chatgpt: false,
    claude: false,
    consultants: false,
  },
  {
    feature: "Behavioral Intelligence (Client Archetypes)",
    caio: true,
    chatgpt: false,
    claude: false,
    consultants: false,
  },
  {
    feature: "Cognitive Governance (Hermes Trust-Broker)",
    caio: true,
    chatgpt: false,
    claude: false,
    consultants: false,
  },
  {
    feature: "Modular Expert Mode (M1–M11)",
    caio: true,
    chatgpt: false,
    claude: false,
    consultants: false,
  },
  {
    feature: "Cost (annual)",
    caio: "$1,188–$35,640",
    chatgpt: "$240",
    claude: "$240",
    consultants: "$50K–$500K+",
  },
  {
    feature: "Delivery Time",
    caio: "Minutes–Hours",
    chatgpt: "Seconds",
    claude: "Seconds",
    consultants: "Weeks–Months",
  },
];