export const plans = [
  {
    name: "Professional",
    price: "$99",
    period: "/mo",
    annualPrice: "$990",
    annualSavings: "Save $198/year",
    description: "Para executivos individuais e consultores",
    priceIds: {
      monthly: "price_1SKD5a2MPzse1ZHQPEtdZGYR",
      annual: "price_1SKD5a2MPzse1ZHQ30D2IwYr",
    },
    features: [
      "Conversas ilimitadas com CAIO",
      "Todas as 48+ Quick Actions",
      "TSI v9.3 Methodology (11 módulos)",
      "Relatórios de análise estratégica",
      "Memos de investimento e frameworks",
      "Calculadoras de ROI e modelagem",
      "Suporte por e-mail",
      "Resposta em até 48h",
    ],
    cta: "Start 14-Day Free Trial",
    popular: false,
  },
  {
    name: "Teams",
    price: "$399",
    period: "/mo",
    annualPrice: "$3,990",
    annualSavings: "Save $798/year",
    description: "Para times de liderança (5+ assentos incluídos)",
    priceIds: {
      monthly: "price_1SKD702MPzse1ZHQovuVBsqL",
      annual: "price_1SKD702MPzse1ZHQnMvEARTU",
    },
    features: [
      "Tudo do Professional",
      "5 assentos incluídos (+ US$ 50/assento adicional)",
      "Workspaces colaborativos",
      "Knowledge Graph completo",
      "Behavioral Intelligence (Client Archetypes)",
      "Mental Model Detection",
      "Base de conhecimento compartilhada",
      "Dashboard de atividade do time",
      "Suporte prioritário (24h response)",
      "Sessões mensais de estratégia",
      "Quick Actions customizadas",
    ],
    cta: "Start 14-Day Free Trial",
    popular: true,
  },
  {
    name: "Enterprise",
    price: "$15,000",
    period: "/mo",
    annualPrice: "$150,000",
    annualSavings: "Save $30,000/year",
    description: "Para Fortune 500, Ibovespa e organizações avançadas",
    priceIds: null,
    isCustom: true,
    features: [
      "Tudo do Teams",
      "Assentos ilimitados",
      "Instância CAIO dedicada",
      "Treino de IA em dados proprietários",
      "White-label disponível",
      "SSO & segurança avançada",
      "Account manager dedicado",
      "Suporte 24/7 prioritário",
      "SLAs customizados",
      "Opção on-premise disponível",
      "Hermes Trust-Broker avançado",
      "Módulos e frameworks sob medida",
    ],
    cta: "Schedule a Call",
    popular: false,
    isEnterprise: true,
  },
];