import {
  Globe,
  Target,
  Code,
  DollarSign,
  Lightbulb,
  BarChart,
  Rocket,
  Layers,
  TrendingUp,
  Users,
  Shield
} from "lucide-react";

export const tsiModules = [
  {
    id: "M1",
    name: "Market Intelligence",
    description: "TAM/SAM/SOM, tendências macro, contexto regulatório e dinâmica de demanda.",
    icon: Globe,
    tag: "Contexto de Mercado",
  },
  {
    id: "M2",
    name: "Competitive Intelligence",
    description: "Posicionamento estratégico, 5 Forças de Porter, matriz competitiva e benchmarking.",
    icon: Target,
    tag: "Concorrência",
  },
  {
    id: "M3",
    name: "Tech & Innovation",
    description: "Diagnóstico de stack, maturidade digital, capacidade de inovação e roadmap tecnológico.",
    icon: Code,
    tag: "Tecnologia",
  },
  {
    id: "M4",
    name: "Financial Modeling",
    description: "DCF, NPV/IRR, análise de sensibilidade, cenários e unit economics por iniciativa.",
    icon: DollarSign,
    tag: "Modelagem Financeira",
  },
  {
    id: "M5",
    name: "Strategic Synthesis",
    description: "Integra EVA, CAIO, CSI e VTE em opções estratégicas claras, comparáveis e acionáveis.",
    icon: Lightbulb,
    tag: "Síntese Estratégica",
    featured: true,
  },
  {
    id: "M6",
    name: "Opportunity Matrix",
    description: "Análise risco-retorno, priorização de portfólio estratégico e alocação inteligente de recursos.",
    icon: BarChart,
    tag: "Portfólio & Priorização",
  },
  {
    id: "M7",
    name: "Implementation & OKRs",
    description: "Roadmap executivo, marcos críticos, OKRs fractais e governança de execução.",
    icon: Rocket,
    tag: "Execução",
  },
  {
    id: "M8",
    name: "Maieutic Reframing",
    description: "Lateral thinking through Socratic questioning, alternative scenarios, and exploration of competitive asymmetries.",
    icon: Layers,
    tag: "Maieutic Mode",
  },
  {
    id: "M9",
    name: "Funding Intelligence",
    description: "Estratégia de capital, tese de investimento, valuation e arquitetura de deal.",
    icon: TrendingUp,
    tag: "Inteligência de Capital",
  },
  {
    id: "M10",
    name: "Behavioral Intelligence",
    description: "Detecção de arquétipos de cliente, padrões de engajamento e análise preditiva de necessidades.",
    icon: Users,
    tag: "Inteligência Comportamental",
  },
  {
    id: "M11",
    name: "Hermes Trust-Broker",
    description: "Governança cognitiva, integridade narrativa, mediação Board-Management e CRV scoring.",
    icon: Shield,
    tag: "Governança Cognitiva",
  },
];