import {
  Globe,
  Target,
  Code,
  DollarSign,
  Lightbulb,
  BarChart,
  Rocket,
  Layers,
  TrendingUp,
  Users,
  Shield
} from "lucide-react";

export const tsiModules = [
  {
    id: "M1",
    name: "Market Intelligence",
    description: "TAM/SAM/SOM, macro trends, regulatory context and demand dynamics.",
    descriptionPT: "TAM/SAM/SOM, tendências macro, contexto regulatório e dinâmica de demanda.",
    icon: Globe,
    tag: "Market Context",
    tagPT: "Contexto de Mercado",
  },
  {
    id: "M2",
    name: "Competitive Intelligence",
    description: "Strategic positioning, Porter's 5 Forces, competitive matrix and benchmarking.",
    descriptionPT: "Posicionamento estratégico, 5 Forças de Porter, matriz competitiva e benchmarking.",
    icon: Target,
    tag: "Competition",
    tagPT: "Concorrência",
  },
  {
    id: "M3",
    name: "Tech & Innovation",
    description: "Stack diagnostics, digital maturity, innovation capacity and tech roadmap.",
    descriptionPT: "Diagnóstico de stack, maturidade digital, capacidade de inovação e roadmap tecnológico.",
    icon: Code,
    tag: "Technology",
    tagPT: "Tecnologia",
  },
  {
    id: "M4",
    name: "Financial Modeling",
    description: "DCF, NPV/IRR, sensitivity analysis, scenarios and unit economics per initiative.",
    descriptionPT: "DCF, NPV/IRR, análise de sensibilidade, cenários e unit economics por iniciativa.",
    icon: DollarSign,
    tag: "Financial Modeling",
    tagPT: "Modelagem Financeira",
  },
  {
    id: "M5",
    name: "Strategic Synthesis",
    description: "Integrates EVA, CAIO, CSI and VTE into clear, comparable and actionable strategic options.",
    descriptionPT: "Integra EVA, CAIO, CSI e VTE em opções estratégicas claras, comparáveis e acionáveis.",
    icon: Lightbulb,
    tag: "Strategic Synthesis",
    tagPT: "Síntese Estratégica",
    featured: true,
  },
  {
    id: "M6",
    name: "Opportunity Matrix",
    description: "Risk-return analysis, strategic portfolio prioritization and intelligent resource allocation.",
    descriptionPT: "Análise risco-retorno, priorização de portfólio estratégico e alocação inteligente de recursos.",
    icon: BarChart,
    tag: "Portfolio & Prioritization",
    tagPT: "Portfólio & Priorização",
  },
  {
    id: "M7",
    name: "Implementation & OKRs",
    description: "Executive roadmap, critical milestones, fractal OKRs and execution governance.",
    descriptionPT: "Roadmap executivo, marcos críticos, OKRs fractais e governança de execução.",
    icon: Rocket,
    tag: "Execution",
    tagPT: "Execução",
  },
  {
    id: "M8",
    name: "Maieutic Reframing",
    description: "Lateral thinking through Socratic questioning, alternative scenarios, and exploration of competitive asymmetries.",
    descriptionPT: "Pensamento lateral através de questionamento socrático, cenários alternativos e exploração de assimetrias competitivas.",
    icon: Layers,
    tag: "Maieutic Mode",
    tagPT: "Modo Maiêutico",
  },
  {
    id: "M9",
    name: "Funding Intelligence",
    description: "Capital strategy, investment thesis, valuation and deal architecture.",
    descriptionPT: "Estratégia de capital, tese de investimento, valuation e arquitetura de deal.",
    icon: TrendingUp,
    tag: "Capital Intelligence",
    tagPT: "Inteligência de Capital",
  },
  {
    id: "M10",
    name: "Behavioral Intelligence",
    description: "Customer archetype detection, engagement patterns and predictive needs analysis.",
    descriptionPT: "Detecção de arquétipos de cliente, padrões de engajamento e análise preditiva de necessidades.",
    icon: Users,
    tag: "Behavioral Intelligence",
    tagPT: "Inteligência Comportamental",
  },
  {
    id: "M11",
    name: "Hermes Trust-Broker",
    description: "Cognitive governance, narrative integrity, ESIOS CAIO.AI-Management mediation and CRV scoring.",
    descriptionPT: "Governança cognitiva, integridade narrativa, mediação ESIOS CAIO.AI-Gestão e CRV scoring.",
    icon: Shield,
    tag: "Cognitive Governance",
    tagPT: "Governança Cognitiva",
  },
];