export const detailedUseCases = [
  {
    title: "M&A Due Diligence",
    role: "VP Corporate Development",
    challenge: "Evaluate 5 acquisition targets in 2 weeks",
    challengePT: "Avaliar 5 targets de aquisição em 2 semanas",
    solution: "CAIO TSI+ runs complete analysis (M1–M11) on each target in hours",
    solutionPT: "CAIO TSI+ roda análise completa (M1–M11) em cada target em poucas horas",
    results: [
      "80% faster than traditional manual analysis",
      "$2M tech debt detected in Target #3 via M3",
      "Target #2 recommended with 25% ROI vs 12% sector average",
    ],
    resultsPT: [
      "80% mais rápido que análise manual tradicional",
      "Tech debt de US$ 2M detectado no Target #3 via M3",
      "Target #2 recomendado com 25% ROI vs 12% média do setor",
    ],
    savings: "$150K in consulting fees avoided",
    savingsPT: "US$ 150K em consulting fees evitados",
    timeframe: "10 days → 2 days",
    timeframePT: "10 dias → 2 dias",
  },
  {
    title: "Market Entry Strategy",
    role: "CEO, B2B SaaS",
    challenge: "European market expansion decision",
    challengePT: "Decisão de expansão para mercado europeu",
    solution: "M1 (Market), M2 (Competitive), M4 (Financial) with Socratic mode",
    solutionPT: "M1 (Mercado), M2 (Competitivo), M4 (Financeiro) com modo Socrático",
    results: [
      "TAM identified: €2.1B with 15% CAGR",
      "GO decision with 88% confidence (CRV scoring)",
      "Underserved €400M segment discovered",
    ],
    resultsPT: [
      "TAM identificado: €2.1B com CAGR de 15%",
      "Decisão GO com 88% de confiança (CRV scoring)",
      "Segmento subatendido de €400M descoberto",
    ],
    savings: "$80K saved vs traditional consulting",
    savingsPT: "US$ 80K economizados vs consultoria tradicional",
    timeframe: "6 weeks → 3 days",
    timeframePT: "6 semanas → 3 dias",
  },
  {
    title: "Digital Transformation Roadmap",
    role: "CTO, Financial Services",
    challenge: "Modernize legacy stack with $5M budget",
    challengePT: "Modernizar stack legada com budget de US$ 5M",
    solution: "M3 (Tech) + M7 (Implementation) in phased rollout",
    solutionPT: "M3 (Tech) + M7 (Implementação) em rollout faseado",
    results: [
      "12 initiatives prioritized by ROI and feasibility",
      "18-month roadmap with fractal OKRs and milestones",
      "Risk-adjusted NPV projected at $8.2M",
    ],
    resultsPT: [
      "12 iniciativas priorizadas por ROI e viabilidade",
      "Roadmap 18 meses com OKRs fractais e milestones",
      "NPV ajustado a risco projetado em US$ 8.2M",
    ],
    savings: "$1.5M avoided in wrong tech choices",
    savingsPT: "US$ 1.5M evitados em escolhas tecnológicas erradas",
    timeframe: "3 months planning → 2 weeks",
    timeframePT: "3 meses de planejamento → 2 semanas",
  },
];